version: '3.8'

services:
  metrics-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
      - PORT=8080
    depends_on:
      - redis
    networks:
      - metrics-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - metrics-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - metrics-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  metrics-network:
    driver: bridge